import { Product } from '../types';

export const products: Product[] = [
  {
    id: 1,
    name: 'Wireless Headphones',
    category: 'Electronics',
    brand: 'Brand A',
    price: 99.99,
    rating: 4.5,
    imageUrl: 'https://example.com/images/headphones.jpg',
  },
  {
    id: 2,
    name: 'Bluetooth Speaker',
    category: 'Electronics',
    brand: 'Brand B',
    price: 49.99,
    rating: 4.0,
    imageUrl: 'https://example.com/images/speaker.jpg',
  },
  {
    id: 3,
    name: 'Running Shoes',
    category: 'Footwear',
    brand: 'Brand C',
    price: 59.99,
    rating: 4.2,
    imageUrl: 'https://example.com/images/shoes.jpg',
  },
  {
    id: 5,
    name: 'Leather Jacket',
    category: 'Clothing',
    brand: 'Brand E',
    price: 199.99,
    rating: 4.7,
    imageUrl: 'https://example.com/images/jacket.jpg',
  },
  {
    id: 4,
    name: 'Smartphone',
    category: 'Electronics',
    brand: 'Brand D',
    price: 300,
    rating: 4.8,
    imageUrl: 'https://example.com/images/smartphone.jpg',
  },
  {
    id: 6,
    name: 'Leather Jacket',
    category: 'Clothing',
    brand: 'Brand E',
    price: 20.99,
    rating: 4.7,
    imageUrl: 'https://example.com/images/jacket.jpg',
  },
  {
    id: 7,
    name: 'Wireless Headphones',
    category: 'Electronics',
    brand: 'Brand A',
    price: 113.99,
    rating: 4.5,
    imageUrl: 'https://example.com/images/headphones.jpg',
  },
  {
    id: 8,
    name: 'Bluetooth Speaker',
    category: 'Electronics',
    brand: 'Brand B',
    price: 23.99,
    rating: 4.0,
    imageUrl: 'https://example.com/images/speaker.jpg',
  },
  {
    id: 9,
    name: 'Running Shoes',
    category: 'Footwear',
    brand: 'Brand C',
    price: 67.99,
    rating: 4.2,
    imageUrl: 'https://example.com/images/shoes.jpg',
  },
  {
    id: 10,
    name: 'Smartphone',
    category: 'Electronics',
    brand: 'Brand D',
    price: 799.99,
    rating: 4.8,
    imageUrl: 'https://example.com/images/smartphone.jpg',
  },
  {
    id: 11,
    name: 'Leather Jacket',
    category: 'Clothing',
    brand: 'Brand E',
    price: 110.99,
    rating: 4.7,
    imageUrl: 'https://example.com/images/jacket.jpg',
  },
  {
    id: 12,
    name: 'Leather Jacket',
    category: 'Clothing',
    brand: 'Brand E',
    price: 89.99,
    rating: 4.7,
    imageUrl: 'https://example.com/images/jacket.jpg',
  },
  {
    id: 13,
    name: 'Smartphone',
    category: 'Electronics',
    brand: 'Brand D',
    price: 88.99,
    rating: 4.8,
    imageUrl: 'https://example.com/images/smartphone.jpg',
  },
  {
    id: 14,
    name: 'Leather Jacket',
    category: 'Clothing',
    brand: 'Brand E',
    price: 97.99,
    rating: 4.7,
    imageUrl: 'https://example.com/images/jacket.jpg',
  },
  {
    id: 15,
    name: 'Leather Jacket',
    category: 'Clothing',
    brand: 'Brand E',
    price: 813.99,
    rating: 4.7,
    imageUrl: 'https://example.com/images/jacket.jpg',
  },
];
